@hostname = localhost
@port = 8080
@host = http://{{hostname}}:{{port}}
@user_id = 123
@authToken = token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IjEyMjM0NCIsInVzZXJuYW1lIjoidGVzdCJ9.KL2a9xW-8iJadE778n-_wRZTy1Md1NuMtmVKc1puQI4

# test GetUser
GET  {{host}}/user/{{user_id}} HTTP/1.1
Authorization: {{authToken}}

###

PUT  {{host}}/user/{{user_id}} HTTP/1.1
Content-Type: text/plain
Authorization: {{authToken}}

{
    "username": "example",
    "first_name": "example_first",
    "last_name": "example_last",
    "age": 24
}

###

DELETE {{host}}/user/{{user_id}} HTTP/1.1
Authorization: {{authToken}}

###

CREATE  {{host}}/user/ HTTP/1.1
Content-Type: text/plain
Authorization: {{authToken}}

{
    "username": "example",
    "first_name": "example_first",
    "last_name": "example_last",
    "age": 24
}


###

POST  {{host}}/auth/login HTTP/1.1
Content-Type: text/plain

{
    "username": "test",
    "password": "122344"
}
