@hostname = localhost
@port = 8080
@host = http://{{hostname}}:{{port}}
@user_id = 123

# test GetUser
GET  {{host}}/user/{{user_id}} HTTP/1.1

###

PUT  {{host}}/user/{{user_id}} HTTP/1.1
Content-Type: text/plain

{
    "username": "example",
    "first_name": "example_first",
    "last_name": "example_last",
    "age": 24
}

###

DELETE {{host}}/user/{{user_id}} HTTP/1.1

###

CREATE  {{host}}/user/ HTTP/1.1
Content-Type: text/plain

{
    "username": "example",
    "first_name": "example_first",
    "last_name": "example_last",
    "age": 24
}


###

POST  {{host}}/authenticate/ HTTP/1.1
Content-Type: text/plain

{
    "username": "test",
    "password": "122344"
}
